import { DocTitleConfig } from 'types/portal-config'

const docTitleConfig: DocTitleConfig = {
  name: 'Welcome to the PsychENCODE Knowledge Portal',
  description:
    'Learn more about the PsychENCODE Consortium’s investigation of genomic influences on neuropsychiatric disease and download large-scale data sets generated by the initiative.',
}

export default docTitleConfig
