import { HomePageHeaderConfig } from 'types/portal-config'

const homePageHeader: HomePageHeaderConfig = {
  summary: `Learn more about the PsychENCODE Consortium’s investigation of genomic influences on neuropsychiatric disease and download large-scale data sets generated by the initiative.`,
  title:
    'Welcome to the PsychENCODE Knowledge Portal',
}

export default homePageHeader
