import * as React from 'react'
import { HomePageHeaderConfig } from 'types/portal-config'

const homePageHeader: HomePageHeaderConfig = {
  summary: (
    <>
    The NCI Division of Cancer Biology supports multiple research programs composed of interdisciplinary communities of scientists who aim to integrate approaches, data, and tools to address important questions in basic and translational cancer research. Discover and download datasets, publications, and other resources generated by these programs.
    </>
  ),
  title:
    'Welcome to the Cancer Complexity Knowledge Portal',
  showBlur: false,
}

export default homePageHeader
