export const facetAliases = {
  grantType: 'Grant Type',
  consortium: 'Program',
  'tissue_or_organ.sv': 'Tissue',
  experimentalStrategy: 'Assay',
  tumorType: 'Disease',
  name: 'Name',
  Title: 'Publication',
  keyInvestigators: 'Key Investigators',
  centerName: 'Center Name',
  studies: 'Studies',
  description: 'Description',
  Consortium: 'Program',
  diseaseType: 'Disease',
  'Publication Year': 'Year',
  grantNumber: 'Grant',
  abstract: 'Abstract',
  species: 'Species',
  summary: 'Summary',
  fileFormat: 'Data Format',
  platform: 'Platform',
  sex: 'Gender',
  tissue: 'Tissue',
  inputDataType: 'Input Data',
  outputDataType: 'Output Data',
  softwareLanguage: 'Language',
  toolName: 'Name'
}