export const buttonColors = {
  colors: [
    '#119488',
    '#58A058',
    '#407BA0',
    '#5BB0B5',
    '#3C4A63',
  ],
}

export const facetAliases = {
  studyName: 'Study Name',
  contact: 'Contact',
  subtype: 'Subtype',
  studyStatus: 'Study Status',
  institutions: 'Institutions',
  datasetName: 'Dataset Name',
  author: 'Author',
  title: 'Title',
  summary: 'Summary',
  studyLeads: 'Study Leads',
  pmid: 'PubMed Id',
  dataStatus: 'Data Status',
  fundingAgency: 'Funding Agency',
  manifestation: 'Manifestation',
  diseaseFocus: 'Disease Focus',
  journal: 'Journal',
  year: 'Year',
  id: 'File ID',
  assay: 'Assay',
  dataType: 'Data Type',
  diagnosis: 'Diagnosis',
  tumorType: 'Tumor Type',
  species: 'Species',
  individualID: 'Individual ID',
  fileFormat: 'File Format',
  dataSubtype: 'Data Subtype',
  nf1Genotype: 'NF1 Genotype',
  nf2Genotype: 'NF2 Genotype',
  consortium: 'Consortium',
  name: 'File Name',
  type: 'Type',
  accessType: 'Access Type'
}
